const projects = [
    {
        id: "coral-plus",
        name: "Coral Plus",
        role: "Full Stack Developer",
        desc: "Company Portfolio Website",
        overview:
            "Coral Plus is a premium company portfolio website built to showcase services, team, and past work for a professional business audience. The site features smooth animations, a modern design system, and fully responsive layouts across all devices.",
        date: "April/2025 — June/2025",
        live: "https://coralplus.ae",
        image: "",
        tech: ["React.js", "Node.js", "Express", "MongoDB", "Tailwind CSS"],
        features: [
            "Responsive multi-page layout",
            "Animated hero and service sections",
            "Contact form with backend integration",
            "Admin panel for content management",
            "SEO optimized structure",
        ],
        link: "#",
    },
    {
        id: "nordicbiogains",
        name: "Nordicbiogains",
        role: "Full Stack Developer",
        desc: "Company Portfolio Website",
        overview:
            "Nordicbiogains is a professional company website for a bioscience and health supplement brand. The project involved building a clean, conversion-focused marketing site with product showcase, blog, and inquiry form functionalities.",
        date: "May/2025 — June/2025",
        live: "https://nordicbiogains.com",
        image: "",
        tech: ["React.js", "Node.js", "Express", "MongoDB", "CSS Modules"],
        features: [
            "Product showcase with filtering",
            "Blog / news section",
            "Customer inquiry form",
            "Mobile-first responsive design",
            "Performance optimized images",
        ],
        link: "#",
    },
    {
        id: "sublet",
        name: "Sublet",
        role: "Frontend Developer",
        desc: "Rental marketplace app for subletting properties.",
        overview:
            "Sublet is a modern rental marketplace platform that connects property owners with renters looking for short-term or sublet arrangements. The frontend delivers an intuitive property browsing experience with advanced filters, map integration, and smooth booking flows.",
        date: "May/2025 — Present",
        live: "https://coralplus.ae",
        image: "",
        tech: ["React.js", "Tailwind CSS", "Redux Toolkit", "Google Maps API"],
        features: [
            "Property listing & search with filters",
            "Interactive map view",
            "Saved listings / wishlist",
            "Owner & renter dashboard",
            "Mobile-responsive design",
        ],
        link: "#",
    },
    {
        id: "inzaar-lms",
        name: "Inzaar LMS",
        role: "Full Stack Development",
        desc: "Learning Management System (Website + Portal)",
        overview:
            "Inzaar LMS is a comprehensive Learning Management System built for educational institutions. It provides a feature-rich student and instructor portal enabling course management, lesson delivery, progress tracking, and assignment submission — all in one unified platform.",
        date: "June/2025 — Present",
        live: "https://inzaar-h795.vercel.app/",
        image: "/images/inzaar.png",
        tech: ["React.js", "Tailwind CSS", "Node.js", "Express.js", "MongoDB", "React query", "React Router", "REST API", "Vite"],
        features: [
            "Course creation and management",
            "Student enrollment & progress tracking",
            "Lesson video & content delivery",
            "Assignment submission & grading",
            "Role-based access (Admin / Moderrator / Student)",
        ],
        link: "#",
    },
    {
        id: "patient-appointment-system",
        name: "Patient Appointment System",
        role: "Full Stack Developer",
        desc: "Appointment and Patient management system for clinic and hospital",
        overview:
            "A full-stack clinic management platform that streamlines patient appointment scheduling, doctor management, and administrative workflows for clinics and hospitals. The system provides real-time availability, automated reminders, and detailed reporting dashboards.",
        date: "June/2025 — Present",
        live: "https://patientaappointmentmanagementsystem.netlify.app/",
        image: "/images/patient_management_system.png",
        tech: ["React.js", "Node.js", "Express.js", "MongoDB", "Tailwind CSS"],
        features: [
            "Patient registration & profile management",
            "Doctor schedule & availability management",
            "Appointment booking with conflict detection",
            "Admin reporting & analytics dashboard",
            "SMS / Email appointment reminders",
        ],
        link: "https://patientaappointmentmanagementsystem.netlify.app/",
    },
];

export default projects;